create table lives (id bigint generated by default as identity, live_date timestamp(6) not null, registration_date timestamp(6) not null, channel_name varchar(255) not null, live_link varchar(255) not null, live_name varchar(255) not null, live_status varchar(255) not null check (live_status in ('SCHEDULED','FINISHED')), primary key (id));
INSERT INTO lives (id, live_name, channel_name, live_date, live_link, live_status, registration_date) VALUES;
(1, 'Explorando Resident Evil', 'Alanzoka', '2024-12-01T19:00:00', 'http://twitch.tv/alanzoka', 'SCHEDULED', '2024-11-26T15:00:00'),;
(2, 'Campeonato de CS:GO', 'CapJoga', '2024-12-03T20:00:00', 'http://twitch.tv/capjoga', 'SCHEDULED', '2024-11-26T15:10:00'),;
(3, 'Minecraft Hardcore Ao Vivo', 'Alanzoka', '2024-11-30T18:00:00', 'http://twitch.tv/alanzoka', 'FINISHED', '2024-11-20T15:00:00'),;
(4, 'FIFA Ultimate Team Partida', 'CapJoga', '2024-12-05T21:00:00', 'http://twitch.tv/capjoga', 'SCHEDULED', '2024-11-26T15:20:00'),;
(5, 'Ranqueada no Valorant', 'Alanzoka', '2024-12-02T17:00:00', 'http://twitch.tv/alanzoka', 'FINISHED', '2024-11-25T15:00:00');
