version: "3.7"
services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  pg-docker:
    image: postgres:14-alpine
    container_name: agendalive-postgresql
    environment:
      POSTGRES_DB: agendalive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5433:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - agendalive-network
  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: agendalive-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@agendalive.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - 5050:80
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - pg-docker
    networks:
      - agendalive-network
# ======================================================================================================================
# REDE
# ======================================================================================================================
networks:
  agendalive-network:
    driver: bridge
